### ISSUE TITLE
feature/SASS-I

### ISSUE THREAD

**Issue by melanierolo** [melanierolo/Coldplay#26]
**Tasks:**
- [x] package.json - node sass . Command : npm run scss
- [x] add _nested_ rules
- [x] add [_variables_](https://sass-lang.com/documentation/variables#advanced-variable-functions) as a way to store information that you want to reuse throughout your stylesheet.
- [x] create and split of [_partial SCSS files_](https://medium.com/ampersand-academy/partials-in-sass-scss-5aae1beee414) that contain little snippets of CSS
- [x] SCSS media queries (@mixin and @include).
- [x] convert .jpeg to .webp for improve the performance

**Comment by melanierolo** [comment]
Resources-articles:
- [Media querie Scss](https://css-tricks.com/approaches-media-queries-sass/)
- [Structuring your Sass Projects
](https://itnext.io/structuring-your-sass-projects-c8d41fa55ed4)
- [Large Scale Application Architecture for CSS with SASS and SMACSS
](https://www.codeproject.com/Tips/843344/Large-Scale-Application-Architecture-for-CSS-with)
- [Cómo organizar los archivos Sass de tu proyecto
](https://latteandcode.medium.com/c%C3%B3mo-organizar-los-archivos-sass-de-tu-proyecto-c8b02242d95)

**Comment by melanierolo** [comment]
[embed code](https://stackoverflow.com/questions/37322148/why-is-instagram-embed-code-only-showing-an-instagram-icon-not-the-image/55414214#55414214)
