### ISSUE TITLE
feature/Sass-II

### ISSUE THREAD

**Issue by melanierolo** [melanierolo/Coldplay#30]
**Tasks:**
- [x] add the ::selection CSS pseudo-element.
- [x] add a Favicon in HTML 
- [x] add keyframes slide-in-top([animista-slide-in-top](https://animista.net/play/entrances/slide-in))
